/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.mycompany.quanlykhachsan.model.Booking;
import controler.HoaDonController;
import controler.RoomController;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import controler.InvoiceController;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.Calendar;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Admin
 */
public class HoaDonDatPhong extends javax.swing.JFrame {

    HoaDonController HDC;

    public HoaDonDatPhong() {
        initComponents();
        HDC = new HoaDonController();
        // Khởi tạo bảng ban đầu (hiển thị tất cả booking khi form mở)
        loadAllBookingsToTable();
        setupYearComboBox();
        String s = (String) cmbYearSelection.getSelectedItem();
        loadChartForSelectedYear(s);
        setupInitialData();
        updateStatistics();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HoaDonTheothangjDialog1 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TongdoanhthujLabel6 = new javax.swing.JLabel();
        DanhSachjLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        reload = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CLosejButton3 = new javax.swing.JButton();
        TongdoanhthuJLB = new javax.swing.JLabel();
        bieudoJD = new javax.swing.JDialog();
        root = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        cmbYearSelection = new javax.swing.JComboBox<>();
        pnlChartContainer = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Bang1 = new javax.swing.JTable();
        bdjButton2 = new javax.swing.JButton();
        ThongKeHoaDonjButton3 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        HoaDonTheothangjDialog1.setMinimumSize(new java.awt.Dimension(652, 520));
        HoaDonTheothangjDialog1.setModal(true);

        jLabel4.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        jLabel4.setText("_______________________________________________________________________________________________________________________");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Lọc danh sách theo tháng :");

        TongdoanhthujLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TongdoanhthujLabel6.setText("Tổng doanh thu trong Tháng 1:");

        DanhSachjLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DanhSachjLabel7.setText("Danh sách số phòng có lần đặt nhiều hơn 1 lần trong Tháng: ");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Phòng", "Số Lần Đặt"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTextField2.setBackground(new java.awt.Color(153, 153, 153));
        jTextField2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Thống Kê Hóa Đơn Theo Tháng : ");
        jTextField2.setToolTipText("");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        reload.setBackground(new java.awt.Color(153, 153, 153));
        reload.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        reload.setForeground(new java.awt.Color(255, 255, 255));
        reload.setText("Reload");
        reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        CLosejButton3.setBackground(new java.awt.Color(153, 153, 153));
        CLosejButton3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        CLosejButton3.setForeground(new java.awt.Color(255, 255, 255));
        CLosejButton3.setText("Back");
        CLosejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLosejButton3ActionPerformed(evt);
            }
        });

        TongdoanhthuJLB.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TongdoanhthuJLB.setForeground(new java.awt.Color(255, 0, 51));
        TongdoanhthuJLB.setText("jLabel9");

        javax.swing.GroupLayout HoaDonTheothangjDialog1Layout = new javax.swing.GroupLayout(HoaDonTheothangjDialog1.getContentPane());
        HoaDonTheothangjDialog1.getContentPane().setLayout(HoaDonTheothangjDialog1Layout);
        HoaDonTheothangjDialog1Layout.setHorizontalGroup(
            HoaDonTheothangjDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonTheothangjDialog1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(HoaDonTheothangjDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reload, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HoaDonTheothangjDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addGroup(HoaDonTheothangjDialog1Layout.createSequentialGroup()
                            .addGroup(HoaDonTheothangjDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CLosejButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(130, 130, 130)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                        .addComponent(DanhSachjLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(HoaDonTheothangjDialog1Layout.createSequentialGroup()
                            .addGroup(HoaDonTheothangjDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TongdoanhthujLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(78, 78, 78)
                            .addGroup(HoaDonTheothangjDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TongdoanhthuJLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        HoaDonTheothangjDialog1Layout.setVerticalGroup(
            HoaDonTheothangjDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonTheothangjDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HoaDonTheothangjDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HoaDonTheothangjDialog1Layout.createSequentialGroup()
                        .addComponent(CLosejButton3)
                        .addGap(33, 33, 33)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HoaDonTheothangjDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HoaDonTheothangjDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TongdoanhthujLabel6)
                    .addComponent(TongdoanhthuJLB))
                .addGap(14, 14, 14)
                .addComponent(DanhSachjLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reload)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setText("BIỂU ĐỒ THỐNG KÊ DOANH THU ");

        jProgressBar3.setBackground(new java.awt.Color(0, 102, 102));

        jProgressBar4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setText("Năm  :");

        cmbYearSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        pnlChartContainer.setLayout(new java.awt.BorderLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton2.setText("Chọn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rootLayout = new javax.swing.GroupLayout(root);
        root.setLayout(rootLayout);
        rootLayout.setHorizontalGroup(
            rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel7)
                .addGap(191, 191, 191)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(cmbYearSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(rootLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlChartContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
                    .addComponent(jProgressBar4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rootLayout.setVerticalGroup(
            rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(cmbYearSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(pnlChartContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bieudoJDLayout = new javax.swing.GroupLayout(bieudoJD.getContentPane());
        bieudoJD.getContentPane().setLayout(bieudoJDLayout);
        bieudoJDLayout.setHorizontalGroup(
            bieudoJDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bieudoJDLayout.createSequentialGroup()
                .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bieudoJDLayout.setVerticalGroup(
            bieudoJDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bieudoJDLayout.createSequentialGroup()
                .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jProgressBar1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setText("THỐNG KÊ HÓA ĐƠN ");

        jProgressBar2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setText("Mục Tìm kiếm nhanh: ");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Bang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null},
                {"", null, null, null, null, null},
                {"", null, null, null, null, null},
                {"", null, null, null, null, null},
                {"", null, null, null, null, null},
                {"", null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CCCD", "ID Phòng", "Check in", "Check out", "Tổng tiền"
            }
        ));
        jScrollPane1.setViewportView(Bang1);

        bdjButton2.setText("Biểu đồ thống kê");
        bdjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdjButton2ActionPerformed(evt);
            }
        });

        ThongKeHoaDonjButton3.setText("Thống Kê Hóa Đơn Theo tháng");
        ThongKeHoaDonjButton3.setToolTipText("");
        ThongKeHoaDonjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongKeHoaDonjButton3ActionPerformed(evt);
            }
        });

        jButton3.setText("Reload");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2)))
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bdjButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ThongKeHoaDonjButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator1)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE))))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bdjButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThongKeHoaDonjButton3)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadAllBookingsToTable() {
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        Bang1.setModel(defaultTableModel);

        // Khởi tạo các cột
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("CCCD");
        defaultTableModel.addColumn("ID Phòng");
        defaultTableModel.addColumn("Check in");
        defaultTableModel.addColumn("Check out");
        defaultTableModel.addColumn("Tổng Tiền");
        defaultTableModel.addColumn("Mã Hóa Đơn"); // Thêm cột này nếu bạn muốn hiển thị Ma_HD
        defaultTableModel.addColumn("Trạng thái HD"); // Thêm cột này nếu bạn muốn hiển thị trạng thái và tô màu

        List<Booking> bookings = HDC.getAllBookings(); // Gọi phương thức từ Controller
        for (Booking bk : bookings) {
            defaultTableModel.addRow(new Object[]{
                bk.getId(),
                bk.getCustomer().getCccd(),
                bk.getRoomId(),
                bk.getCheckInDate(),
                bk.getCheckOutDate(),
                bk.getTongTien(),
                bk.getMaHD(), // Lấy Ma_HD từ Booking object
                bk.getStatus() // Lấy Status từ Booking object
            });
        }

    }

    private void loadBookingsBySearchTermToTable(String searchRoomIdTerm) {
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        Bang1.setModel(defaultTableModel);

        // Khởi tạo lại các cột cho bảng (phải khớp với thứ tự các cột khi thêm hàng)
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("CCCD");
        defaultTableModel.addColumn("ID Phòng");
        defaultTableModel.addColumn("Check in");
        defaultTableModel.addColumn("Check out");
        defaultTableModel.addColumn("Tổng Tiền");
        defaultTableModel.addColumn("Mã Hóa Đơn");
        defaultTableModel.addColumn("Trạng thái HD");

        // Gọi phương thức tìm kiếm gần đúng từ Controller
        List<Booking> bookings = HDC.searchBookingsByRoomIdPartial(searchRoomIdTerm);

        if (bookings.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy booking nào cho ID phòng gần đúng: '" + searchRoomIdTerm + "'", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }

        for (Booking bk : bookings) {
            defaultTableModel.addRow(new Object[]{
                bk.getId(),
                bk.getCustomer().getCccd(),
                bk.getRoomId(),
                bk.getCheckInDate(),
                bk.getCheckOutDate(),
                bk.getTongTien(),
                bk.getMaHD(),
                bk.getStatus()
            });
        }

    }

    private void setupYearComboBox() {
        Set<Integer> years = HDC.getAvailableYears();
        cmbYearSelection.removeAllItems(); // Xóa các item cũ nếu có
        for (Integer year : years) {
            cmbYearSelection.addItem(String.valueOf(year));
        }
        // Chọn năm gần nhất (vì TreeSet sắp xếp giảm dần trong DAO)
        if (!years.isEmpty()) {
            cmbYearSelection.setSelectedItem(years.iterator().next());
        }
    }

    private void loadChartForSelectedYear(String s) {
        String selectedYears = s;

        if (selectedYears == null) {
            pnlChartContainer.removeAll(); // Xóa biểu đồ cũ nếu không có năm nào được chọn
            pnlChartContainer.revalidate();
            pnlChartContainer.repaint();
            return;
        }
        int selectedYear = Integer.parseInt(selectedYears);

        // Lấy dữ liệu doanh thu từ Controller
        Map<Integer, Double> monthlyRevenueData = HDC.getMonthlyRevenueForYear(selectedYear);

        // Tạo Dataset cho JFreeChart
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (int month = 1; month <= 12; month++) {
            double revenue = monthlyRevenueData.getOrDefault(month, 0.0); // Lấy doanh thu, mặc định là 0 nếu không có
            dataset.addValue(revenue, "Doanh thu", getMonthName(month)); // "Doanh thu" là series key, tên tháng là category key
        }

        // Tạo biểu đồ cột
        JFreeChart chart = ChartFactory.createBarChart(
                "Doanh thu theo tháng năm " + selectedYear, // Tiêu đề biểu đồ
                "Tháng", // Nhãn trục X
                "Doanh thu (VNĐ)", // Nhãn trục Y
                dataset, // Dataset
                PlotOrientation.VERTICAL, // Hướng biểu đồ
                true, // Hiển thị legend
                true, // Hiển thị tooltips
                false // Không hiển thị URLs
        );

        // Tùy chỉnh màu sắc (tùy chọn)
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(Color.lightGray);
        plot.setRangeGridlinePaint(Color.white);
        plot.getRenderer().setSeriesPaint(0, new Color(79, 129, 189)); // Màu cột

        // Tạo ChartPanel và thêm vào container
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(pnlChartContainer.getWidth(), pnlChartContainer.getHeight())); // Kích thước bằng container

        pnlChartContainer.removeAll(); // Xóa biểu đồ cũ
        pnlChartContainer.add(chartPanel, BorderLayout.CENTER);
        pnlChartContainer.revalidate(); // Cập nhật layout
        pnlChartContainer.repaint();    // Vẽ lại
    }

    /**
     * Trả về tên tháng dựa trên số tháng.
     */
    private String getMonthName(int month) {
        switch (month) {
            case 1:
                return "Tháng 1";
            case 2:
                return "Tháng 2";
            case 3:
                return "Tháng 3";
            case 4:
                return "Tháng 4";
            case 5:
                return "Tháng 5";
            case 6:
                return "Tháng 6";
            case 7:
                return "Tháng 7";
            case 8:
                return "Tháng 8";
            case 9:
                return "Tháng 9";
            case 10:
                return "Tháng 10";
            case 11:
                return "Tháng 11";
            case 12:
                return "Tháng 12";
            default:
                return "";
        }
    }

  

    private void setupInitialData() {
        // Đặt tháng hiện tại vào JComboBox khi cửa sổ mở
        Calendar now = Calendar.getInstance();
        int currentMonth = now.get(Calendar.MONTH); // Calendar.MONTH là 0-based
        jComboBox1.setSelectedIndex(currentMonth); // Chọn tháng hiện tại

        // Cập nhật thống kê ngay lập tức
        updateStatistics();
    }
    // Trong lớp HoaDonThongKeTheoThangUI

    private void updateStatistics() {
        int selectedMonth = jComboBox1.getSelectedIndex() + 1; // Lấy tháng (1-12)
        int currentYear = Calendar.getInstance().get(Calendar.YEAR); // Lấy năm hiện tại
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("ID Phòng");
        tableModel.addColumn("Số Lần Đặt");
        jTable2.setModel(tableModel); // Gán model cho JTable

        // Cập nhật JLabel hiển thị tiêu đề
        TongdoanhthujLabel6.setText("Tổng doanh thu trong Tháng " + selectedMonth + " Năm " + currentYear + ":");

        // Lấy và hiển thị tổng doanh thu
        double totalRevenue = HDC.getTotalMonth(selectedMonth);
        TongdoanhthuJLB.setText(String.format("%,.2f VND", totalRevenue)); // Định dạng tiền tệ

        // Cập nhật bảng danh sách phòng
        tableModel.setRowCount(0); // Xóa tất cả các hàng hiện có trong bảng
        Map<Integer, Integer> rooms = HDC.getRoomsBookedMultipleTimes(selectedMonth);

        if (rooms.isEmpty()) {
            tableModel.addRow(new Object[]{"Không có phòng nào đặt nhiều hơn 1 lần trong tháng này.", ""});
        } else {
            for (Map.Entry<Integer, Integer> entry : rooms.entrySet()) {
                tableModel.addRow(new Object[]{entry.getKey(), entry.getValue()});
            }
        }
    }

    private void ThongKeHoaDonjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongKeHoaDonjButton3ActionPerformed
        // TODO add your handling code here:
        HoaDonTheothangjDialog1.setLocationRelativeTo(null);
        HoaDonTheothangjDialog1.setVisible(true);

        HoaDonTheothangjDialog1.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_ThongKeHoaDonjButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        updateStatistics();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void CLosejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLosejButton3ActionPerformed
        // TODO add your handling code here:
        HoaDonTheothangjDialog1.dispose();

    }//GEN-LAST:event_CLosejButton3ActionPerformed

    private void bdjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdjButton2ActionPerformed
        // TODO add your handling code here:
        bieudoJD.setSize(1140, 650);
        bieudoJD.setLocationRelativeTo(null);
        bieudoJD.setVisible(true);

    }//GEN-LAST:event_bdjButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String TextString = jTextField1.getText().trim();
        if (TextString.isEmpty()) {
            // Nếu trường tìm kiếm trống, tải lại tất cả dữ liệu
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ID phòng để tìm kiếm.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            loadAllBookingsToTable();
            return;
        }
        loadBookingsBySearchTermToTable(TextString);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        loadAllBookingsToTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String s = (String) cmbYearSelection.getSelectedItem();
        loadChartForSelectedYear(s);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadActionPerformed
        // TODO add your handling code here:
        updateStatistics();
    }//GEN-LAST:event_reloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonDatPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Bang1;
    private javax.swing.JButton CLosejButton3;
    private javax.swing.JLabel DanhSachjLabel7;
    private javax.swing.JDialog HoaDonTheothangjDialog1;
    private javax.swing.JButton ThongKeHoaDonjButton3;
    private javax.swing.JLabel TongdoanhthuJLB;
    private javax.swing.JLabel TongdoanhthujLabel6;
    private javax.swing.JButton bdjButton2;
    private javax.swing.JDialog bieudoJD;
    private javax.swing.JComboBox<String> cmbYearSelection;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel pnlChartContainer;
    private javax.swing.JButton reload;
    private javax.swing.JPanel root;
    // End of variables declaration//GEN-END:variables
}
