/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import QuanLyKhachSan.dao.JDBCConnection;
import QuanLyKhachSan.dao.RoomDAO;
import controler.RoomController;
import java.awt.Color;
import javax.swing.JFrame;
import java.awt.Window;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    public EmployManager employManager;
    public HoaDonDatPhong hddp;
    public ServiceDetail sd;
    public RoomManager rm;
    private Map<Integer, JButton> phongButtons = new HashMap<>();
    private RoomController roomController;
    

    ;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null); // Căn giữa màn hình

        this.employManager = new EmployManager();
        this.hddp = new HoaDonDatPhong();
        this.sd = new ServiceDetail();
        this.rm = new RoomManager();
        roomController = new RoomController(new RoomDAO(JDBCConnection.getConnection()));
        phongButtons.put(101,Phong101jButton1 );
    }

//    public static <T extends ServiceNRoom> void configureAndShow(T window, String title) {
//        window.setLocationRelativeTo(null);
//        window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        window.setTenphong(title); // Ví dụ: setTitle() có sẵn trong JFrame
//        window.setVisible(true);
//    }

    public static void Show1(java.awt.Window window) {
        window.setLocationRelativeTo(null);

        if (window instanceof JFrame frame) {
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }

        window.setVisible(true);
    }

    public void setPhongDaCheckIn(int roomId) {
    JButton btn = phongButtons.get(roomId);
    if (btn != null) {
        btn.setBackground(Color.GREEN);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        QuanlykhachangjLabel = new javax.swing.JLabel();
        QuanLyNhanVienjLabel4 = new javax.swing.JLabel();
        QuanLyPhongjLabel5 = new javax.swing.JLabel();
        QuanLyDichVujLabel6 = new javax.swing.JLabel();
        ThongKeDoanhThujLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Phong101jButton1 = new javax.swing.JButton();
        P102jButton2 = new javax.swing.JButton();
        P103jButton4 = new javax.swing.JButton();
        P104jButton3 = new javax.swing.JButton();
        P105jButton5 = new javax.swing.JButton();
        P106jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ỨNG DỤNG QUẢN LÝ NHÀ HÀNG");
        setBackground(new java.awt.Color(255, 51, 51));
        setMinimumSize(new java.awt.Dimension(970, 700));
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMaximumSize(new java.awt.Dimension(980, 600));
        bg.setMinimumSize(new java.awt.Dimension(980, 600));
        bg.setPreferredSize(new java.awt.Dimension(980, 600));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Quanlykhachsan\\src\\main\\java\\ICON\\leaf_188333 (1).png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel2.setText("GREEN LEAVES HOTEL");

        QuanlykhachangjLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        QuanlykhachangjLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Quanlykhachsan\\src\\main\\java\\ICON\\icons8-human-50.png")); // NOI18N
        QuanlykhachangjLabel.setText("  Quản lý khách hàng");
        QuanlykhachangjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanlykhachangjLabelMouseClicked(evt);
            }
        });

        QuanLyNhanVienjLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        QuanLyNhanVienjLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Quanlykhachsan\\src\\main\\java\\ICON\\icons8-employee-64.png")); // NOI18N
        QuanLyNhanVienjLabel4.setText("Quản lý nhân viên ");
        QuanLyNhanVienjLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanLyNhanVienjLabel4MouseClicked(evt);
            }
        });

        QuanLyPhongjLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        QuanLyPhongjLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Quanlykhachsan\\src\\main\\java\\ICON\\icons8-bed-48.png")); // NOI18N
        QuanLyPhongjLabel5.setText("    Quản lý phòng");
        QuanLyPhongjLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanLyPhongjLabel5MouseClicked(evt);
            }
        });

        QuanLyDichVujLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        QuanLyDichVujLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Quanlykhachsan\\src\\main\\java\\ICON\\icons8-service-64.png")); // NOI18N
        QuanLyDichVujLabel6.setText("  Quản lý dịch vụ");
        QuanLyDichVujLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanLyDichVujLabel6MouseClicked(evt);
            }
        });

        ThongKeDoanhThujLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        ThongKeDoanhThujLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Quanlykhachsan\\src\\main\\java\\ICON\\icons8-report-50.png")); // NOI18N
        ThongKeDoanhThujLabel7.setText("     Thống Kê Doanh thu");
        ThongKeDoanhThujLabel7.setToolTipText("");
        ThongKeDoanhThujLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThongKeDoanhThujLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(QuanlykhachangjLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuanLyNhanVienjLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QuanLyDichVujLabel6)
                                    .addComponent(ThongKeDoanhThujLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(QuanLyPhongjLabel5)))))))
                .addGap(7, 7, 7))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QuanlykhachangjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuanLyNhanVienjLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuanLyPhongjLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuanLyDichVujLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThongKeDoanhThujLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 20, 20));

        Phong101jButton1.setText("PHÒNG 101");
        Phong101jButton1.setToolTipText("");
        Phong101jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phong101jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(Phong101jButton1);

        P102jButton2.setText("PHÒNG 102");
        P102jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P102jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(P102jButton2);

        P103jButton4.setText("PHÒNG 103");
        P103jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P103jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(P103jButton4);

        P104jButton3.setText("PHÒNG 104");
        P104jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P104jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(P104jButton3);

        P105jButton5.setText("PHÒNG 105");
        P105jButton5.setActionCommand("PHÒNG 105");
        P105jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P105jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(P105jButton5);

        P106jButton6.setText("PHÒNG 106");
        P106jButton6.setActionCommand("PHÒNG 106");
        P106jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P106jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(P106jButton6);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuanlykhachangjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanlykhachangjLabelMouseClicked
        CustomerManager customerManager = new CustomerManager();

        customerManager.setLocationRelativeTo(null);
        customerManager.setVisible(true);
        customerManager.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_QuanlykhachangjLabelMouseClicked

    private void Phong101jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phong101jButton1ActionPerformed
        // TODO add your handling code here:
             roomController.openRoomFrame(this,101);

    }//GEN-LAST:event_Phong101jButton1ActionPerformed

    private void P102jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P102jButton2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_P102jButton2ActionPerformed

    private void QuanLyNhanVienjLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyNhanVienjLabel4MouseClicked
        // TODO add your handling code here:
        this.Show1(employManager);

    }//GEN-LAST:event_QuanLyNhanVienjLabel4MouseClicked

    private void ThongKeDoanhThujLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeDoanhThujLabel7MouseClicked
        // TODO add your handling code here:
        this.Show1(hddp);

    }//GEN-LAST:event_ThongKeDoanhThujLabel7MouseClicked

    private void QuanLyDichVujLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyDichVujLabel6MouseClicked
        // TODO add your handling code here:
        this.Show1(sd);

    }//GEN-LAST:event_QuanLyDichVujLabel6MouseClicked

    private void P103jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P103jButton4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_P103jButton4ActionPerformed

    private void P104jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P104jButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_P104jButton3ActionPerformed

    private void P105jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P105jButton5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_P105jButton5ActionPerformed

    private void P106jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P106jButton6ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_P106jButton6ActionPerformed

    private void QuanLyPhongjLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyPhongjLabel5MouseClicked
        // TODO add your handling code here:
        this.Show1(rm);
    }//GEN-LAST:event_QuanLyPhongjLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton P102jButton2;
    private javax.swing.JButton P103jButton4;
    private javax.swing.JButton P104jButton3;
    private javax.swing.JButton P105jButton5;
    private javax.swing.JButton P106jButton6;
    private javax.swing.JButton Phong101jButton1;
    private javax.swing.JLabel QuanLyDichVujLabel6;
    private javax.swing.JLabel QuanLyNhanVienjLabel4;
    private javax.swing.JLabel QuanLyPhongjLabel5;
    private javax.swing.JLabel QuanlykhachangjLabel;
    private javax.swing.JLabel ThongKeDoanhThujLabel7;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
